### ISSUE TITLE
Tuple field getters

### ISSUE THREAD

**Issue by robrix** [robrix/Prelude#44]
a la `fst` and `snd` but not named that because oy

**Comment by robrix** [comment]
(Note for @nikita-leonov or anyone else interested in tackling this: `first` and `second` would be preferable names.)

**Comment by nikita-leonov** [comment]
Nice. In our code base we actually used first & second too, as it is more inline with Swift conventions. I will find time this week on converting our quick & nimble tests into XCTests and will provide PR. Thanks!

**Comment by nikita-leonov** [comment]
Added in #48. There are also suggestion / question for other tuple related operators.

**Comment by robrix** [comment]
Closed by #48. Thanks again @nikita-leonov :bow: :grin:
