### ISSUE TITLE
1.7.0 doesn't conform to semantic versioning

### ISSUE THREAD

**Issue by ikesyo** [robrix/Prelude#52]
The release is dedicated for Swift 3 and apparently breaks the backwards compatibility: https://github.com/robrix/Prelude/releases/tag/1.7.0. That should be tagged as `2.0.0`.

@robrix @335g

**Comment by ikesyo** [comment]
Hmm, 1.5.0 (for Swift 1.2) to 1.6.0 (for Swift 2) was also introducing the breaking changes. 😅

**Comment by 335g** [comment]
Thanks @ikesyo ✋ 

I will fix it because I think also that it should be tagged as `2.0.0`.

**Comment by 335g** [comment]
I fixed it 👍
