### ISSUE TITLE
CocoaPods require update, as the latest version released in CocoaPods is 1.4

### ISSUE THREAD

**Issue by nikita-leonov** [robrix/Prelude#58]
I requested access rights to pods trunk from Kyle Fuller. I will update cocoapods as soon as I get an access.

**Comment by nikita-leonov** [comment]
@robrix I need a help :) Can you write him a direct message in a twitter? I assume he is following you. I tried to reach him through multiple channels, but unsuccessfully. He is currently the only owner of Prelude trunk in Cocoapods :(

**Comment by robrix** [comment]
cc @kylef

**Comment by robrix** [comment]
@nikita-leonov: He does not, but I’ve pinged him.

**Comment by nikita-leonov** [comment]
Released. Thanks to all participants :)
